config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  root 'api/v1/events#show', :id => 1

  post '/events/:id', to: 'events#buy_ticket'
  post '/tickets/test', to: 'tickets#test', as: 'buy_ticket'

  resources :tickets
  resources :spaces
  
  resources :companies, shallow: true do
    resources :events
  end

  namespace :api do
    namespace :v1 do
      resources :companies, shallow: true do
        resources :events, shallow: true do
          resources :tickets
          resources :spaces
        end
      end
    end
  end

  match '*path', to: 'application#not_found', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :events
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :tickets
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :venue
  belongs_to :company

  has_many :tickets, dependent: :destroy 
  has_many :spaces, dependent: :destroy 
  has_one :grid, dependent: :destroy

  accepts_nested_attributes_for :grid

  before_validation :default_event

  def default_event
    self.company_id ||= 1
    self.venue_id ||= 1
    self.grid ||= build_grid(rows: 1, cols: 1)
    self.instantiate_spaces(self.grid.rows, self.grid.cols) if self.spaces.empty?
  end

  def instantiate_spaces(rows, cols)
    size = (cols * rows)
    4.times do |i|
      self.spaces.new(status: 'available', position: i + 1)
    end
  end
end

app/models/grid.rb
class Grid < ApplicationRecord
  ROW_LIMIT = 10
  COL_LIMIT = 10

  belongs_to :event

  validates :rows, comparison: { greater_than: 0 }
  validates :cols, comparison: { greater_than: 0 }

  # def get_space(i, k)
  #   space = self.spaces.where(position: self.get_index(i, k)).first
  # end

  # def get_ticket(i, k)
  #   ticket = self.event.tickets.where(seat: get_index(i, k)).first
  # end

  # def get_index(i, k)
  #   return i * cols + k
  # end

  before_validation :default_grid
  
  private

  def default_grid
    self.rows ||= ROW_LIMIT
    self.cols ||= COL_LIMIT
    self.cols = COL_LIMIT if self.cols > COL_LIMIT
    self.rows = ROW_LIMIT if self.rows > ROW_LIMIT
  end

end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/space.rb
class Space < ApplicationRecord
  include Available

  belongs_to :event
  
  validates_presence_of :position
  validates :position, numericality: { greater_than: 0 }
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :customer
  belongs_to :event
  # validates :seat, uniqueness: { scope: :event,
  #                                message: "one seat # per event" }
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :events
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/grid_helper.rb
module GridHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/showings_helper.rb
module ShowingsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/layouts/_button.html.erb
<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2
               px-4 rounded m-2">
  <%= yield %>
</button>

app/views/layouts/_error.html.erb
<% if component.errors.any? %>
<p class="text-red-500">
  <% component.errors.each do |error| %>
  <%= error.full_message %>
  <% end %>
</p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-gray-700 text-white p-10 mt-20">
  <div class="w-full mx-auto max-w-screen-xl p-4 flex items-center
              justify-between text-sm text-gray-400">
    <p>© 2023 SeatFinder™ All Rights Reserved</p>
    <ul class="flex items-center font-medium">
      <li>
        <a href="#" class="hover:underline mr-6 ">About</a>
      </li>
      <li>
        <a href="#" class="hover:underline mr-6">Privacy Policy</a>
      </li>
      <li>
        <a href="#" class="hover:underline mr-6">Licensing</a>
      </li>
      <li>
        <a href="#" class="hover:underline">Contact</a>
      </li>
    </ul>
  </div>
</footer>

app/views/layouts/_form.html.erb
<%= form_with model: model do |form| %>
    <%= yield form %>
<% end %>

app/views/layouts/_link_button.html.erb
<%= render "layouts/button" do %>
<%= link_to link, data: defined?(data) ? data : nil do %>
<%= label %>      
<% end %>
<% end %>

app/views/layouts/_main.html.erb
<main class="flex flex-col justify-between min-h-screen">
    <div>
        <%= render "layouts/navbar" %>
    </div>
    <%= yield %>
    <div>
        <%= render "layouts/footer" %>
    </div>
</main>

app/views/layouts/_messages.html.erb
<% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
<% end %>
<% if alert.present? %>
    <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="notice"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="bg-gray-700 text-white">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
      <%= link_to root_url, class: "flex items-center" do %>
      <%=  image_tag "theatre_camera.png", class: "h-8 mr-3", alt: "camera" %>
      <span class="self-center text-2xl font-semibold">SeatFinder</span>
      <% end %>
      <ul class="font-medium flex space-x-8">
        <li><%= link_to "Home", root_url %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/alternate.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>alternate layout</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <main class="min-h-screen grid grid-cols-2">
          <%= yield %>
      </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeatFinder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/main" %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render(PageComponent.new()) do  %>
    <%= render(ContentComponent.new(title: "admin")) do %>
        <%= render(PanelsComponent.new()) do %>
            <%= render(PanelComponent.new(title: "events")) do %>
                <ul>
                    <% @events.each do |event| %>
                        <li>
                            <%= link_to event.id, event %>
                        </li>
                    <% end %>
                </ul>
                <%= link_to "New Event", new_event_path %>
            <% end %>
        <% end %>
    <% end %>
<% end %>

app/views/shared/_search_filters.html.erb
<%= form_with model: search do |form| %>
  <h1>Search form:</h1>
  <fieldset>
    <%= yield form %>
  </fieldset>
  <p>
    <%= form.submit "Search" %>
  </p>
<% end %>