config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  root 'api/v1/events#show', :id => 1

  post '/events/:id', to: 'events#buy_ticket'
  post '/tickets/test', to: 'tickets#test', as: 'buy_ticket'

  resources :tickets
  resources :spaces
  
  resources :companies, shallow: true do
    resources :events
  end

  namespace :api do
    namespace :v1 do
      resources :companies, shallow: true do
        resources :events, shallow: true do
          resources :tickets
          resources :spaces
        end
      end
    end
  end

  match '*path', to: 'application#not_found', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :events
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :tickets
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :venue
  belongs_to :company

  has_many :tickets, dependent: :destroy 
  has_many :spaces, dependent: :destroy 
  has_one :grid, dependent: :destroy

  accepts_nested_attributes_for :grid

  before_validation :default_event

  def default_event
    self.company_id ||= 1
    self.venue_id ||= 1
    self.grid ||= build_grid(rows: 1, cols: 1)
    self.instantiate_spaces(self.grid.rows, self.grid.cols) if self.spaces.empty?
  end

  def instantiate_spaces(rows, cols)
    size = (cols * rows)
    4.times do |i|
      self.spaces.new(status: 'available', position: i + 1)
    end
  end
end

app/models/grid.rb
class Grid < ApplicationRecord
  ROW_LIMIT = 10
  COL_LIMIT = 10

  belongs_to :event

  validates :rows, comparison: { greater_than: 0 }
  validates :cols, comparison: { greater_than: 0 }

  # def get_space(i, k)
  #   space = self.spaces.where(position: self.get_index(i, k)).first
  # end

  # def get_ticket(i, k)
  #   ticket = self.event.tickets.where(seat: get_index(i, k)).first
  # end

  # def get_index(i, k)
  #   return i * cols + k
  # end

  before_validation :default_grid
  
  private

  def default_grid
    self.rows ||= ROW_LIMIT
    self.cols ||= COL_LIMIT
    self.cols = COL_LIMIT if self.cols > COL_LIMIT
    self.rows = ROW_LIMIT if self.rows > ROW_LIMIT
  end

end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/space.rb
class Space < ApplicationRecord
  include Available

  belongs_to :event
  
  validates_presence_of :position
  validates :position, numericality: { greater_than: 0 }
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :customer
  belongs_to :event
  # validates :seat, uniqueness: { scope: :event,
  #                                message: "one seat # per event" }
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :events
end

app/controllers/api/v1/tickets_controller.rb
class Api::V1::TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tickets or /tickets.json
  def index
    @event = Event.find(params[:event_id])
    @tickets = @event.tickets
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new    
  end

  # GET /tickets/1/edit
  def edit
  end

  def test
    @event = Event.find(params[:event_id])
    @customer = Customer.create
    @ticket = @event.tickets.build
    @ticket.seat = params[:seat]
    @ticket.customer = @customer

    respond_to do |format|
      format.html { render :new, notice: "Ticket was successfully created." }
      format.json { render :show, status: :created, location: @ticket }
    end
  end

  # POST /tickets or /tickets.json
  def create
    @event = Event.find(params[:event_id])
    @ticket = @event.tickets.create(ticket_params)    
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to ticket_path(@ticket), notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { render json: @ticket, status: :ok }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def ticket_params
    params.require(:ticket).permit(:customer_id, :name, :seat)
  end
end

app/controllers/grid_controller.rb
class GridController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @events = Event.all
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tickets or /tickets.json
  def index
    @event = Event.find(params[:event_id])
    @tickets = @event.tickets
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new    
  end

  # GET /tickets/1/edit
  def edit
  end

  def test
    @event = Event.find(params[:event_id])
    @customer = Customer.create
    @ticket = @event.tickets.build
    @ticket.seat = params[:seat]
    @ticket.customer = @customer

    respond_to do |format|
      format.html { render :new, notice: "Ticket was successfully created." }
      format.json { render :show, status: :created, location: @ticket }
    end
  end

  # POST /tickets or /tickets.json
  def create
    @event = Event.find(params[:event_id])
    @ticket = @event.tickets.create(ticket_params)    
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to ticket_path(@ticket), notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { render json: @ticket, status: :ok }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def ticket_params
    params.require(:ticket).permit(:customer_id, :name, :seat)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/grid_helper.rb
module GridHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/showings_helper.rb
module ShowingsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: [ space, ticket ], class: "contents") do |form| %>
    <% if ticket.errors.any? %>
        <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
            <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

            <ul>
                <% ticket.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="my-5">
        <%= form.label :name %>
        <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", :required => true %>
    </div>
    <%= form.hidden_field :seat %>
    <%= form.hidden_field :customer_id %>
    <%= form.hidden_field :space_id %>
    <div class="inline">
        <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
<% end %>

app/views/tickets/_ticket.html.erb
<div id="<%= dom_id ticket %>">
    <p class="my-5">
        <strong class="block font-medium mb-1">Name:</strong>
        <%= ticket.name %>
    </p>

    <p class="my-5">
        <strong class="block font-medium mb-1">Seat:</strong>
        <%= ticket.seat %>
    </p>

    <p class="my-5">
        <strong class="block font-medium mb-1">Customer:</strong>
        <%= ticket.customer_id %>
    </p>

    <% if action_name != "show" %>
        <%= link_to "Show this ticket", ticket, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
        <%= link_to 'Edit this ticket', edit_ticket_path(ticket), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
        <hr class="mt-6">
    <% end %>
</div>

app/views/tickets/create.turbo_stream.erb
<%= turbo_stream.update @ticket.space %>
<%= turbo_stream.update 'new_message', '' %>

app/views/tickets/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">New ticket</h1>
</div>

<%= turbo_frame_tag 'new_message' do %>
    <%= render "form", ticket: @ticket, space: @space %>
<% end %>

app/views/tickets/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">

      <%= turbo_frame_tag 'new_message' do %>
        <%= render @ticket %>
    <% end %>
    <%#= link_to 'Edit this ticket', edit_ticket_path(@ticket), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this ticket', ticket_path(@ticket), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to event', @ticket.space.grid.event, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>